version: 2.1

jobs:
  terraform_init:
    docker:
      - image: hashicorp/terraform:1.0.2
    working_directory: /app
    steps:
      - checkout
      - run:
          name: Initialize Terraform
          command: terraform init

  terraform_plan:
    docker:
      - image: hashicorp/terraform:1.0.2
    working_directory: /app
    steps:
      - attach_workspace:
          at: /app
      - run:
          name: Generate Terraform plan
          command: terraform plan -out plan.out

  terraform_apply:
    docker:
      - image: hashicorp/terraform:1.0.2
    working_directory: /app
    steps:
      - attach_workspace:
          at: /app
      - run:
          name: Apply Terraform changes
          command: terraform apply -auto-approve plan.out

  terraform_destroy:
    docker:
      - image: hashicorp/terraform:1.0.2
    working_directory: /app
    steps:
      - attach_workspace:
          at: /app
      - run:
          name: Destroy Terraform resources
          command: terraform destroy -auto-approve

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - terraform_init
      - terraform_plan:
          requires:
            - terraform_init
      - terraform_apply:
          requires:
            - terraform_plan
      - terraform_destroy:
          requires:
            - terraform_apply

